#!/bin/sh
#/********************************************************************** 
# Freeciv - Copyright (C) 1996 - A Kjeldberg, L Gregersen, P Unold
# script by Rene Schalburg
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2, or (at your option)
#   any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#***********************************************************************/

BUILDDIR=`dirname $0`
EXENAME=freeciv-server

if test "x$FREECIV_DATA_PATH" = "x" ; then
  if test "x$FREECIV_PATH" = "x" ; then
    FREECIV_DATA_PATH=".:data:~/.freeciv/2.5"
  else
    FREECIV_DATA_PATH="${FREECIV_PATH}"
  fi
fi
FREECIV_DATA_PATH="${FREECIV_DATA_PATH}:/home/parallels/Documents/freeciv-project/data:/home/parallels/Documents/freeciv-project/data"
export FREECIV_DATA_PATH

if test "x$FREECIV_PATH" = "x" ; then
  FREECIV_PATH=".:data:~/.freeciv:~/.freeciv/2.5"
fi
FREECIV_PATH="${FREECIV_PATH}:/home/parallels/Documents/freeciv-project"
export FREECIV_PATH

if test "x$FREECIV_SAVE_PATH" = "x" ; then
  FREECIV_SAVE_PATH=".:~/.freeciv/saves"
fi
FREECIV_SAVE_PATH="${FREECIV_SAVE_PATH}:/home/parallels/Documents/freeciv-project:/home/parallels/Documents/freeciv-project"
export FREECIV_SAVE_PATH

if test "x$FREECIV_SCENARIO_PATH" = "x" ; then
  FREECIV_SCENARIO_PATH=".:data/scenarios:~/.freeciv/2.5/scenarios:~/.freeciv/scenarios"
fi
FREECIV_SCENARIO_PATH="${FREECIV_SCENARIO_PATH}:/home/parallels/Documents/freeciv-project/data/scenarios:/home/parallels/Documents/freeciv-project/data/scenarios"
export FREECIV_SCENARIO_PATH

[ -x $BUILDDIR/server/$EXENAME ] && EXE=$BUILDDIR/server/$EXENAME
[ -x $BUILDDIR/$EXENAME ] && EXE=$BUILDDIR/$EXENAME

if [ "$EXE" = "" ]; then
  echo $0: Unable to find $EXENAME.
  exit 1
fi

exec $EXE ${1+"$@"}
